server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: example-service-route
          uri: lb://example-service
          predicates:
            - Path=/api/example/**
