spring.application.name=demo
server.port=8080

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=${SPRING_AI_OPENAI_BASE_URL:https://openai.vocareum.com}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-3-small
