package com.ecommerce.rma.event;

/**
 * TODO (Step 5 – Kafka Event Publishing):
 * This record represents the Kafka message that is published to the
 * {@code "returns-topic"} topic when a return request is <b>approved</b>.
 *
 * <p>It is the payload for the CQRS "write" side of the system: once published,
 * {@code DashboardService} consumes it and adds it to the read-model so it
 * appears in the GraphQL dashboard query.
 *
 * <p><b>How Kafka serializes this record:</b>
 * Spring Kafka is configured (in {@code application.properties}) to use
 * {@code JsonSerializer} for the producer value. This means this record will
 * be automatically converted to JSON before being placed on the topic wire.
 * On the consumer side, {@code JsonDeserializer} converts it back.
 *
 * <p><b>Your task in RmaService Step 5:</b>
 * After the policy check approves the return, construct and publish this event:
 * <pre>{@code
 * var event = new ReturnApprovedEvent(
 *         request.customerId(),
 *         analysis.itemType(),   // from the ReturnAnalysis you parsed in Step 3
 *         policyDecision         // the reason string from the policy AI call in Step 4
 * );
 * kafkaTemplate.send("returns-topic", request.customerId(), event);
 * }</pre>
 *
 * <p><b>Your task in DashboardService Step 6:</b>
 * Add a {@code @KafkaListener} method that receives this event and stores it in
 * the {@code dashboardView} map keyed by {@code customerId}.
 *
 * @param customerId Identifier of the customer whose return was approved.
 * @param itemType   Category of the returned item (e.g. "electronics", "clothing").
 * @param reason     The policy-based reason for approval, as generated by the AI.
 */
public record ReturnApprovedEvent(

        String customerId,
        String itemType,
        String reason

) {}