server:
  port: 8080

spring:
  application:
    name: order-service

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    instances:
      payment:
        # TODO (Step 1): Configure 3 max attempts with exponential backoff
        max-attempts: 1
  circuitbreaker:
    instances:
      payment:
        # TODO (Step 2): Configure sliding window size, failure-rate-threshold, wait-duration
        # TODO (Step 2): Configure ignoreExceptions for InvalidCreditCardException
        sliding-window-size: 10
